name: Start push

on:
  push:
    branches:
      - master

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codes
        uses: actions/checkout@v3

      - name: Log in to Docker Container Registry
        uses: docker/login-action@v3
        with:
          username: danielfarag
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Docker image
        run: docker build -t danielfarag/python-django:latest .
  
      - name: Push Docker image to Registry
        run: docker push danielfarag/python-django:latest